name: Auto Update

on:
  schedule:
    # تغییر به دقیقه ۱۴ هر ساعت - این یعنی فرار از ترافیک سنگین دقیقه ۰
    - cron: '14 * * * *'
  workflow_dispatch: # دکمه اجرای دستی برای مواقع اضطراری

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    # این خط باعث می‌شود اگر اجرای قبلی هنوز تمام نشده، اجرای جدید منتظر نماند و لغو نشود
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # آپدیت به نسخه ۴ برای سرعت بیشتر

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install telethon

      - name: Run Extraction Script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
        run: python main.py

            - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # اضافه کردن فایل
          git add sub.txt
          
          # بررسی اینکه آیا تغییری وجود دارد یا خیر (برای جلوگیری از ارور)
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')"
            # استفاده از توکن برای اجازه نهایی
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          fi

