name: Auto Update

on:
  schedule:
    - cron: '35 * * * *' # اجرا در دقیقه ۳۵ هر ساعت
  workflow_dispatch:

# تعریف صریح دسترسی در سطح فایل
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # استفاده از توکن پیش‌فرض برای احراز هویت
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install telethon

      - name: Run Script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
        run: python main.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add sub.txt
          
          # اگر تغییری در فایل نباشد، بدون ارور خارج شود
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')"
            git push
          fi
