name: Auto Update

on:
  push:
    branches:
      - none_trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow is disabled
        run: echo "This workflow is currently disabled."
